# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate JSON

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: npm install & start
      uses: actions/setup-node@v3
    - run: npm ci
    - run: npm start
    - name: commit & push
      uses: EndBug/add-and-commit@v9.1.3
